version: '3.8'

services:
  node:
    privileged: true
    init: true
    build:
      context: node
      dockerfile: Dockerfile
    hostname: node
    user: vscode
    volumes:
      - ../:/home/vscode/workspace
    tty: true
  pubsub:
    build:
      context: pubsub
      dockerfile: Dockerfile
    hostname: pubsub
    tty: true
