version: '3.8'

services:
  node:
    privileged: true
    # init: true
    build:
      context: "$HOME/workspace/.devcontainer/node"
      dockerfile: Dockerfile
      args:
        - PUBSUB_EMULATOR_HOST=pubsub:8043
        - PUBSUB_PROJECT_ID=abc
        - TOPID=test-topic
    hostname: node
    user: vscode
    volumes:
      - "$HOME/workspace:/home/vscode/workspace"
    tty: true
    depends_on:
      pubsub:
        condition: service_healthy
  pubsub:
    build:
      context: "$HOME/workspace/.devcontainer/pubsub"
      dockerfile: Dockerfile
      args:
        - PUBSUB_EMULATOR_HOST=pubsub:8043
        - PUBSUB_PROJECT_ID=abc
    hostname: pubsub
    user: root
    tty: true
    healthcheck:
      test: '/healthcheck.sh || exit 1'
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 50s
