# https://github.com/marketplace/actions/run-jest
name: test
on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '!v*'

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # https://docs.github.com/ja/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm キャッシュファイルは Linux/macOS の「~/.npm」に保存される
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      # キャッシュ用にコンテナの外側でインストールしておく.
      # コンテナ内で再度インストールするとほとんどのパッケージはインストール済で扱われる、と思う.
      # (もっと良い方法は?)
      - name: Install pacckages
        run: npm ci

      - name: Run test inside Dev Container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            npm ci
            npm run lint:type-check
            npm run test
